### ISSUE TITLE
Values are not updated

### ISSUE THREAD

**Issue by tooh** [dhayab/homebridge-withings-air-quality#2]
@dhayab , thanks for making this plugin. Had give up hope that somebody would make the effort.

After using the plugin for a couple of weeks, it seems that the temperature value is not updated.

I checked on the Withings portal and they are correct there.

Can you advise me how to debug your plugin to assert that my assumptions are correct?

**Comment by dhayab** [comment]
Hi, thanks for reporting this issue. What's happening is that the plugin logs into the Withings website just once, on initialization, and stores the session cookie for subsequent API calls. After a few days, the session expires, so all requests will fail.

I'll add a way to refresh the session cookie, so that these errors won't happen again.
